name: "image_classifier"
backend: "onnxruntime"
max_batch_size: 32

input [
  {
    name: "input_image"
    data_type: TYPE_FP32
    dims: [224, 224, 3]
  }
]

output [
  {
    name: "dense_1"
    data_type: TYPE_FP32
    dims: [5]
  }
]

# Dynamic Batching собирает несколько одиночных запросов в один батч.
dynamic_batching {
  preferred_batch_size: [4, 8, 16]
  max_queue_delay_microseconds: 100000
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
